### ISSUE TITLE
implement Ds\Hashable

### ISSUE THREAD

**Issue by mjpvandenberg** [zlikavac32/php-enum#2]
After reading https://medium.com/@rtheunissen/efficient-data-structures-for-php-7-9dda7af674cd I've been using the Ds\Map and Ds\Set collections in my code. For an object to be usable as a key in Ds\Map and to ensure uniqueness in Ds\Set, the object's class needs to implement Ds\Hashable. 

Would you consider implementing Hashable in Enum? 

The current workaround is to use $enum->name() as a map key, but this is suboptimal, and sets cannot be determined uniqueness.

I can create a PR if you'd like.

**Comment by mjpvandenberg** [comment]
Alternatively, can we allow more than 1 level of inheritance? That way, I can create a base class for all my actual enums, where the base class extends \Zlikavac32\Enum\Enum and implements Ds\Hashable. This is currently not allowed.

**Comment by zlikavac32** [comment]
@mjpvandenberg Hi, this is a good point. I don't think that adding interface directly to Enum class would make other users (if any) happy, since they would need this extension. If I'm correct, they plan to ditch PHP implementation so they'd need native library.

I'll see what I can do, since I had a plan to remove that constraint (1 level of inheritance)

**Comment by zlikavac32** [comment]
@mjpvandenberg Current idea is the following:

- allow more than one level of inheritance
- disallow for any enum class in the chain to have `enumerate` method except for `Enum` and the class defined by `static`
